/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HelpSeeker;

/**
 *
 * @author samar
 */
public class HelpSeekerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HelpSeekerJPanel
     */
    public HelpSeekerJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageProfile = new javax.swing.JButton();
        lblHelpSeeker = new javax.swing.JLabel();
        btnCreateRequest = new javax.swing.JButton();
        lblProvideTestimony = new javax.swing.JButton();
        btnViewMeals = new javax.swing.JButton();

        lblManageProfile.setText("Manage Profile");

        lblHelpSeeker.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        lblHelpSeeker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHelpSeeker.setText("Help Seeker");

        btnCreateRequest.setText("Create Request");

        lblProvideTestimony.setText("Provide Testimony");

        btnViewMeals.setText("View Meals");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHelpSeeker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreateRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewMeals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProvideTestimony, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblManageProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(568, 568, 568))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblHelpSeeker)
                .addGap(59, 59, 59)
                .addComponent(btnCreateRequest)
                .addGap(50, 50, 50)
                .addComponent(btnViewMeals)
                .addGap(50, 50, 50)
                .addComponent(lblProvideTestimony)
                .addGap(50, 50, 50)
                .addComponent(lblManageProfile)
                .addGap(235, 235, 235))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateRequest;
    private javax.swing.JButton btnViewMeals;
    private javax.swing.JLabel lblHelpSeeker;
    private javax.swing.JButton lblManageProfile;
    private javax.swing.JButton lblProvideTestimony;
    // End of variables declaration//GEN-END:variables
}
