/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HelpSeeker;

/**
 *
 * @author samar
 */
public class TestimonyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestimonyJPanel
     */
    public TestimonyJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProvideTestimony = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        cbLocation = new javax.swing.JComboBox<>();
        lblMode = new javax.swing.JLabel();
        cbMode = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblQuality = new javax.swing.JLabel();
        cbExcellent = new javax.swing.JCheckBox();
        cbGood = new javax.swing.JCheckBox();
        cbAverage = new javax.swing.JCheckBox();
        cbDissatisfied = new javax.swing.JCheckBox();
        btnSend = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblProvideTestimony.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        lblProvideTestimony.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProvideTestimony.setText("Provide Testimony");

        lblLocation.setText("Location:");

        cbLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NGO", "School", "Hospital", "Government" }));

        lblMode.setText("Mode:");

        cbMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivery", "Dine-In" }));

        lblDate.setText("Date:");

        lblQuality.setText("Quality:");

        cbExcellent.setText("Excellent");

        cbGood.setText("Good");

        cbAverage.setText("Average");

        cbDissatisfied.setText("Dissatisfied");
        cbDissatisfied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDissatisfiedActionPerformed(evt);
            }
        });

        btnSend.setText("Send");

        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblProvideTestimony, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLocation)
                            .addComponent(lblMode)
                            .addComponent(lblDate)
                            .addComponent(lblQuality))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbDissatisfied)
                                .addGap(50, 50, 50)
                                .addComponent(btnSend))
                            .addComponent(cbAverage)
                            .addComponent(cbGood)
                            .addComponent(cbExcellent)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDate)
                                .addComponent(cbMode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbLocation, 0, 190, Short.MAX_VALUE)))
                        .addGap(431, 431, 431)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnBack)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblProvideTestimony)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocation)
                    .addComponent(cbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMode)
                    .addComponent(cbMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuality)
                    .addComponent(cbExcellent))
                .addGap(18, 18, 18)
                .addComponent(cbGood)
                .addGap(18, 18, 18)
                .addComponent(cbAverage)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDissatisfied)
                    .addComponent(btnSend))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbDissatisfiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDissatisfiedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDissatisfiedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSend;
    private javax.swing.JCheckBox cbAverage;
    private javax.swing.JCheckBox cbDissatisfied;
    private javax.swing.JCheckBox cbExcellent;
    private javax.swing.JCheckBox cbGood;
    private javax.swing.JComboBox<String> cbLocation;
    private javax.swing.JComboBox<String> cbMode;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMode;
    private javax.swing.JLabel lblProvideTestimony;
    private javax.swing.JLabel lblQuality;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
