/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.EnterpriseAdmin;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Enterprise.MealShare;
import Business.Enterprise.NGOEnterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import ui.Auth.LoginJPanel;
import ui.Donor.ViewDonationHistory;

/**
 *
 * @author samar
 */
public class EnterpriseAdminJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    Organization organization;
    Business business;
    
    /**
     * Creates new form NGOSupervisorJPanel
     */
    public EnterpriseAdminJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, Business business) {
        initComponents();
        this.setBackground(new java.awt.Color(102, 153, 255));
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.account = account;
        this.enterprise = enterprise;
        displayName(enterprise.getName());
        if(enterprise instanceof NGOEnterprise){
            btnRequestDonation.setVisible(true);
            btnViewDonationHistory.setVisible(true);
        }else{
            btnRequestDonation.setVisible(false);
            btnViewDonationHistory.setVisible(false);
        }
        
        if(enterprise instanceof MealShare){
            btnCreateMeals.setVisible(false);
            btnManageMeals.setVisible(false);
        }
    }
    
    
    private void displayName(String name){
        lblNonGovernmentalOrganization.setText("Enterprise: "+ name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNonGovernmentalOrganization = new javax.swing.JLabel();
        btnCreateMeals = new javax.swing.JButton();
        btnManageMeals = new javax.swing.JButton();
        btnManageProfile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnRequestDonation = new javax.swing.JButton();
        btnViewDonationHistory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lblNonGovernmentalOrganization.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        lblNonGovernmentalOrganization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNonGovernmentalOrganization.setText("Non-Governmental Organization");

        btnCreateMeals.setText("Create Meals");
        btnCreateMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMealsActionPerformed(evt);
            }
        });

        btnManageMeals.setText("Manage Meals");
        btnManageMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMealsActionPerformed(evt);
            }
        });

        btnManageProfile.setText("Manage Oragnization Employee");
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });

        jButton1.setText("Manage Organization");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Manage User");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnRequestDonation.setText("Request Donation");
        btnRequestDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestDonationActionPerformed(evt);
            }
        });

        btnViewDonationHistory.setText("View Donation History");
        btnViewDonationHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDonationHistoryActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNonGovernmentalOrganization, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRequestDonation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewDonationHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateMeals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageMeals, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNonGovernmentalOrganization)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnManageProfile)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2)
                        .addGap(35, 35, 35)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateMeals)
                        .addGap(40, 40, 40)
                        .addComponent(btnManageMeals)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRequestDonation)
                        .addGap(40, 40, 40)
                        .addComponent(btnViewDonationHistory)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMealsActionPerformed
        // TODO add your handling code here:
        CreateMealJPanel createMealJPanel = new CreateMealJPanel(userProcessContainer, enterprise, account, business);
        business.redirection(userProcessContainer, createMealJPanel.getClass().getName(), createMealJPanel);
    }//GEN-LAST:event_btnCreateMealsActionPerformed

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        // TODO add your handling code here:
        ManageOrganizationEmployeeJPanel manageOrganizationEmployeeJPanel = new ManageOrganizationEmployeeJPanel(userProcessContainer, this.enterprise, account, business, this.enterprise.getOrganizationDirectory());
        business.redirection(userProcessContainer, manageOrganizationEmployeeJPanel.getClass().getName(), manageOrganizationEmployeeJPanel);
    }//GEN-LAST:event_btnManageProfileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, this.enterprise, account, business);
        business.redirection(userProcessContainer, manageOrganizationJPanel.getClass().getName(), manageOrganizationJPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        ManageUserJPanel manageUserJPanel = new ManageUserJPanel(userProcessContainer, this.enterprise, account, business);
        business.redirection(userProcessContainer, manageUserJPanel.getClass().getName(), manageUserJPanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginJPanel loginJPanel = new LoginJPanel(userProcessContainer, business);
        this.business.redirection(userProcessContainer, loginJPanel.getClass().getName(), loginJPanel);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRequestDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestDonationActionPerformed
        // TODO add your handling code here:
        RequestDonation requestDonation = new RequestDonation(userProcessContainer, enterprise, account, business);
        this.business.redirection(userProcessContainer, requestDonation.getClass().getName(), requestDonation);
    }//GEN-LAST:event_btnRequestDonationActionPerformed

    private void btnViewDonationHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDonationHistoryActionPerformed
        // TODO add your handling code here:
        ViewDonationHistoryEntr requestDonation = new ViewDonationHistoryEntr(userProcessContainer, account, enterprise, organization, business);
        this.business.redirection(userProcessContainer, requestDonation.getClass().getName(), requestDonation);
    }//GEN-LAST:event_btnViewDonationHistoryActionPerformed

    private void btnManageMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMealsActionPerformed
        // TODO add your handling code here:
        ManageMealsJPanel manageMealsJPanel = new ManageMealsJPanel(userProcessContainer, enterprise, account, business);
        this.business.redirection(userProcessContainer, manageMealsJPanel.getClass().getName(), manageMealsJPanel);
    }//GEN-LAST:event_btnManageMealsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateMeals;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageMeals;
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnRequestDonation;
    private javax.swing.JButton btnViewDonationHistory;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNonGovernmentalOrganization;
    // End of variables declaration//GEN-END:variables
}
