/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.EnterpriseAdmin;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samar
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {
    
    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    UserAccount account;
    Business business;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.business = business;
        this.account = account;
        this.directory = enterprise.getOrganizationDirectory();
        populateOrganizationTable();
        populateOrganizationComboBox();
    }
    
    final public void populateOrganizationComboBox()
    {   
        cbOrganizationType.removeAllItems();
    
        if(enterprise.getEnterpriseType().getValue().equals(EnterpriseType.NGO.getValue()))
        {
            cbOrganizationType.addItem(Type.Donor.getValue());
        }
        else if(enterprise.getEnterpriseType().getValue().equals(EnterpriseType.MealShare.getValue()))
        {
            cbOrganizationType.addItem(Type.HelpSeeker.getValue());  
            cbOrganizationType.addItem(Type.Supervisor.getValue()); 
        }
        else if(enterprise.getEnterpriseType().getValue().equals(EnterpriseType.Government.getValue()))
        {
            cbOrganizationType.addItem(Type.CommunityOutreach.getValue());  
        }
        else if(enterprise.getEnterpriseType().getValue().equals(EnterpriseType.School.getValue()))
        {
            cbOrganizationType.addItem(Type.Volunteer.getValue());     
            cbOrganizationType.addItem(Type.Transport.getValue());
        }
        else if(enterprise.getEnterpriseType().getValue().equals(EnterpriseType.Hospital.getValue()))
        {
            cbOrganizationType.addItem(Type.Nutritionist.getValue());     
        }      
    }

    private void populateOrganizationTable(){
        DefaultTableModel model = (DefaultTableModel) tblManageOrganization.getModel();
        
        model.setRowCount(0);
        
        for (Organization organization : directory.getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrgId();
            row[1] = organization;
            
            model.addRow(row);
        }
    }
    
    public Type getEnterPriseType(String name){        
        if(name.equals(Type.Admin.getValue()))
        {
            return Type.Admin;
        }
        else if(name.equals(Type.CommunityOutreach.getValue()))
        {
            return Type.CommunityOutreach;
        }
        else if(name.equals(Type.Donor.getValue()))
        {
            return Type.Donor;
        }
        else if(name.equals(Type.HelpSeeker.getValue()))
        {
            return Type.HelpSeeker;
        }
        else if(name.equals(Type.Nutritionist.getValue()))
        {
            return Type.Nutritionist;
        }
        else if(name.equals(Type.Supervisor.getValue()))
        {
            return Type.Supervisor;
        }
        else if(name.equals(Type.Transport.getValue()))
        {
            return Type.Transport;
        }
        else if(name.equals(Type.Volunteer.getValue()))
        {
            return Type.Volunteer;
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageOrganization = new javax.swing.JLabel();
        lblAddOrganization = new javax.swing.JLabel();
        lblOrganizationType = new javax.swing.JLabel();
        cbOrganizationType = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageOrganization = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblManageOrganization.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        lblManageOrganization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageOrganization.setText("Manage Organization");

        lblAddOrganization.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblAddOrganization.setText("Add Organization");

        lblOrganizationType.setText("Organization Type:");

        cbOrganizationType.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cbOrganizationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donor" }));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblManageOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(tblManageOrganization);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblManageOrganization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddOrganization)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOrganizationType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdd)
                                    .addComponent(cbOrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnBack))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblManageOrganization)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAddOrganization)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrganizationType)
                            .addComponent(cbOrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(164, 164, 164))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        Type type = getEnterPriseType((String) cbOrganizationType.getSelectedItem());
        
        if(type == null)
        {
            JOptionPane.showMessageDialog(this, "Please select a organization!", "warning",JOptionPane.PLAIN_MESSAGE);
            return;     
        }
        for(Organization org: directory.getOrganizationList())
        {
            if (type.getValue().equals(org.getName()))
            {
                JOptionPane.showMessageDialog(null, "The organization already exists!", "warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        directory.addOrganization(type);
        populateOrganizationTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblManageOrganization.getSelectedRow();
        if(selectedRow >= 0)
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Would you like to delete the row ", "warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION)
            {

                Organization org = (Organization) tblManageOrganization.getValueAt(selectedRow, 1);
                 directory.deleteOrganization(org);
            }
            populateOrganizationTable();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select a row", "warning",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        EnterpriseAdminJPanel enterpriseAdminJPanel = new EnterpriseAdminJPanel(userProcessContainer, enterprise, account, business);
        business.redirection(userProcessContainer, enterpriseAdminJPanel.getClass().getName(), enterpriseAdminJPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cbOrganizationType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddOrganization;
    private javax.swing.JLabel lblManageOrganization;
    private javax.swing.JLabel lblOrganizationType;
    private javax.swing.JTable tblManageOrganization;
    // End of variables declaration//GEN-END:variables
}
