/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.EnterpriseAdmin;

import Business.Business;
import Business.Common.ValidateStrings;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Person.HelpSeeker;
import Business.Person.Person;
import Business.Person.Volunteer;
import Business.UserAccount.UserAccount;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samar
 */
public class ManageOrganizationEmployeeJPanel extends javax.swing.JPanel {

    private OrganizationDirectory organizationDir;
    private JPanel userProcessContainer;
    Business business;
    UserAccount account;
    Enterprise enterprise;
    
    /**
     * Creates new form ManageOrganizationEmployeeJPanel
     */
    public ManageOrganizationEmployeeJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, Business business, OrganizationDirectory organizationDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = organizationDir;
        this.business = business;
        this.account = account;
        this.enterprise = enterprise;
        this.setBackground(new java.awt.Color(102, 153, 255));
        addInputVerifiers();
        populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageOrganizationEmployee = new javax.swing.JLabel();
        lblCreateEmployee = new javax.swing.JLabel();
        lblOrganization1 = new javax.swing.JLabel();
        cbOrganizationEmp = new javax.swing.JComboBox<>();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageOrganizationEmployee = new javax.swing.JTable();
        lblOrganization = new javax.swing.JLabel();
        cbOrganization = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();

        lblManageOrganizationEmployee.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        lblManageOrganizationEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageOrganizationEmployee.setText("Manage Organization Employee");

        lblCreateEmployee.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblCreateEmployee.setText("Create Employee");

        lblOrganization1.setText("Organization:");

        cbOrganizationEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donor Organization" }));

        lblFirstName.setText("First Name:");

        lblLastName.setText("Last Name:");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        tblManageOrganizationEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(tblManageOrganizationEmployee);

        lblOrganization.setText("Organization:");

        cbOrganization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donor Organization" }));
        cbOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrganizationActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblManageOrganizationEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCreateEmployee)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                            .addComponent(lblFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                            .addComponent(txtLastName))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBack)
                                    .addGap(212, 212, 212)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOrganization)
                                .addGap(18, 18, 18)
                                .addComponent(cbOrganization, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOrganization1)
                                .addGap(29, 29, 29)
                                .addComponent(cbOrganizationEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblManageOrganizationEmployee)
                .addGap(48, 48, 48)
                .addComponent(lblCreateEmployee)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganization1)
                    .addComponent(cbOrganizationEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrganization)
                    .addComponent(cbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCreate))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(101, 101, 101))
        );
    }// </editor-fold>//GEN-END:initComponents

    private Organization getOrganization(String name){
        if(name != null){
            for (Organization organization : organizationDir.getOrganizationList()){
                if(name.equals(organization.toString())){
                    return organization;
                }
            }
        }
        return null;
    }
    
    private void cbOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrganizationActionPerformed
        // TODO add your handling code here:
        String org = (String) cbOrganization.getSelectedItem();
        
        if(org != null){
            for (Organization organization : organizationDir.getOrganizationList()){
                if(org.equals(organization.toString())){
                    populateEmployeeAndPeopleTable(organization);
                }

            }
        }
    }//GEN-LAST:event_cbOrganizationActionPerformed

    final public void populateOrganizationComboBox(){
        cbOrganization.removeAllItems();
        
        for (Organization organization : organizationDir.getOrganizationList()){
            cbOrganization.addItem(organization.toString());
        }
    }
    
    final public void populateOrganizationEmpComboBox(){
        cbOrganizationEmp.removeAllItems();
        
        for(Organization organization : organizationDir.getOrganizationList()){

            if(!(organization.getName().equals("Volunteer Organization")) && 
                    !(organization.getName().equals("Admin")) &&
                    !(organization.getName().equals("HelpSeeker Organization")))
            {
            cbOrganizationEmp.addItem(organization.toString());
            }
        }
    }
    
    
    private void addInputVerifiers() {
        InputVerifier stringValidation = new ValidateStrings();
        txtFirstName.setInputVerifier(stringValidation);
        txtLastName.setInputVerifier(stringValidation);
    }
    
    private void populateEmployeeAndPeopleTable(Organization organization){
        DefaultTableModel model = (DefaultTableModel) tblManageOrganizationEmployee.getModel();
        
        model.setRowCount(0);
        System.out.println("organization.getName() "+ organization.getName());
        
        switch (organization.getName()) {
            case "HelpSeeker Organization" -> {
                for(HelpSeeker person : organization.getPersonDirectory().getCustomerLsit()){
                    Object[] row = new Object[2];
                    row[0] = person.getHelpSeekerId();
                    row[1] = person.getName();
                    model.addRow(row);
                }
            }
            case "Volunteer Organization" -> {
                for(Volunteer person : organization.getPersonDirectory().getVolunteerList()){
                    Object[] row = new Object[2];
                    row[0] = person.getVolunteerId();
                    row[1] = person.getName();
                    model.addRow(row);
                }
            }
            default -> {
                for(Person person : organization.getPersonDirectory().getPersonList()){
                    Object[] row = new Object[2];
                    row[0] = person.getPersonId();
                    row[1] = person.getName();
                    model.addRow(row);
                }
            }
        }
       
    }
    
    
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        if(txtFirstName.getText().trim().isEmpty() || txtLastName.getText().trim().isEmpty() 
                || cbOrganization.getSelectedIndex()<0)
        {
            JOptionPane.showMessageDialog(null, "Please Enter data in all the fields");
            return;    
        }
        try
        {
            Organization organization = getOrganization((String) cbOrganization.getSelectedItem());
            String firstName = txtFirstName.getText();
            String lastName = txtLastName.getText();

            Person person = organization.getPersonDirectory().addPerson();    

            person.setFirstName(firstName);
            person.setLastName(lastName);
            person.setName();

            JOptionPane.showMessageDialog(null, "Employee has been created successfully", "success",JOptionPane.PLAIN_MESSAGE);
            resetFields();
            populateEmployeeAndPeopleTable(organization);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please Enter valid data in all the fields");
            return;   
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        EnterpriseAdminJPanel enterpriseAdminJPanel = new EnterpriseAdminJPanel(userProcessContainer, enterprise, account, business);
        business.redirection(userProcessContainer, enterpriseAdminJPanel.getClass().getName(), enterpriseAdminJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    
    public void resetFields()
    {
     txtFirstName.setText("");
     txtLastName.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> cbOrganization;
    private javax.swing.JComboBox<String> cbOrganizationEmp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateEmployee;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblManageOrganizationEmployee;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblOrganization1;
    private javax.swing.JTable tblManageOrganizationEmployee;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
