/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.EnterpriseAdmin;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Roles.Role;
import Business.Roles.Role.RoleType;
import Business.UserAccount.UserAccount;
import Business.WrokQueue.DonationRequest;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aniketgiram
 */
public class RequestDonation extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    Business business;
    HashMap<Integer, UserAccount> users;

    /**
     * Creates new form RequestDonation
     */
    public RequestDonation(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.account = account;
        this.enterprise = enterprise;
        this.setBackground(new java.awt.Color(102, 153, 255));
        users = new HashMap<>();
        populateCombo();
    }

    private void populateCombo() {
        cbDonor.removeAllItems();
        int index = 1;
        cbDonor.addItem("Please select a donor");
        for (Organization e : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : e.getUserAccountDirectory().getUserAccountList()) {
                cbDonor.addItem(ua.getPerson().getName());
                users.put(index++, ua);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRequestDonation = new javax.swing.JLabel();
        cbDonor = new javax.swing.JComboBox<>();
        lblDonor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        lblComments = new javax.swing.JLabel();
        btnRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblRequestDonation.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        lblRequestDonation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequestDonation.setText("Request Donation");

        lblDonor.setText("Select Donor:");

        txtComments.setColumns(20);
        txtComments.setRows(5);
        jScrollPane1.setViewportView(txtComments);

        lblComments.setText("Comments:");

        btnRequest.setText("Request Donation");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRequestDonation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(btnRequest))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDonor)
                            .addComponent(lblComments))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(cbDonor, 0, 192, Short.MAX_VALUE))))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblRequestDonation)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDonor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDonor))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComments))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequest)
                    .addComponent(btnBack))
                .addContainerGap(300, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        EnterpriseAdminJPanel enterpriseAdminJPanel = new EnterpriseAdminJPanel(userProcessContainer, enterprise, account, business);
        business.redirection(userProcessContainer, enterpriseAdminJPanel.getClass().getName(), enterpriseAdminJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        int index = cbDonor.getSelectedIndex();
        String comment = txtComments.getText();
        if(comment.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter comment");
            return;
        }
        
        DonationRequest donationRequest = new DonationRequest();
        donationRequest.setSender(account);
        donationRequest.setRequestDate(new Date());
        donationRequest.setMessage(comment);
        donationRequest.setStatus("Sent");
        donationRequest.setRequestDate(new Date());
        
        UserAccount user = users.get(index);
        System.out.println("Requesting donation to usr " + user);
        System.out.println("User " + user.getPerson().getName());
        user.getWorkQueue().getWorkRequestList().add(donationRequest);
        account.getWorkQueue().getWorkRequestList().add(donationRequest);
        JOptionPane.showMessageDialog(this, "Donation request sent", "Information", JOptionPane.INFORMATION_MESSAGE);
        txtComments.setText("");
    }//GEN-LAST:event_btnRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JComboBox<String> cbDonor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblDonor;
    private javax.swing.JLabel lblRequestDonation;
    private javax.swing.JTextArea txtComments;
    // End of variables declaration//GEN-END:variables
}
