/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Nutritionist;

import Business.Business;
import Business.Common.Meal;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WrokQueue.MealWorkRequest;
import Business.WrokQueue.WorkQueue;
import Business.WrokQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aishwarya Dhandore
 */
public class ViewMealsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    Business business;
    Organization organization;
    /**
     * Creates new form ViewMealsJPanel
     */
    public ViewMealsJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, Organization organization, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.account = account;
        this.enterprise = enterprise;
        this.organization = organization;
        checkForWorkRequest();
        populateTable();
        this.setBackground(new java.awt.Color(102, 153, 255));
    }
    
    private void checkForWorkRequest(){
     if(account.getWorkQueue().getWorkRequestList().isEmpty()){
         JOptionPane.showMessageDialog(this, "No Meals Assigned", "warning", JOptionPane.WARNING_MESSAGE);
     }
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblViewMeals.getModel();

        model.setRowCount(0);
        
        for(WorkRequest w: account.getWorkQueue().getWorkRequestList()){
            if(w instanceof MealWorkRequest){
                MealWorkRequest m = (MealWorkRequest) w;
                Object row[] = new Object[6];
                Meal meal = m.getMealByID(m.getSendDataRequestId()) != null ? m.getMealByID(m.getSendDataRequestId()) : null;
                row[0] = m;
                row[1] = m.getSender().getUserName();
                row[2] = m.getMessage();
                row[3] = meal != null ? m.getMealByID(m.getSendDataRequestId()).getProtein() : "";
                row[4] = meal != null ? m.getMealByID(m.getSendDataRequestId()).getCarbs() : "";
                row[5] = meal != null ? m.getMealByID(m.getSendDataRequestId()).getCalories(): ""; 
                model.addRow(row);
            } 
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewMeals = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewMeals = new javax.swing.JTable();
        txtProtien = new javax.swing.JTextField();
        txtCalories = new javax.swing.JTextField();
        txtCarbs = new javax.swing.JTextField();
        lblProtien = new javax.swing.JLabel();
        lblCarbs = new javax.swing.JLabel();
        lblCalories = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblViewMeals.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblViewMeals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewMeals.setText("View Meals");

        tblViewMeals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Organization", "Meal content", "Protein", "Carbs", "Calories"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewMeals);
        if (tblViewMeals.getColumnModel().getColumnCount() > 0) {
            tblViewMeals.getColumnModel().getColumn(0).setResizable(false);
            tblViewMeals.getColumnModel().getColumn(1).setResizable(false);
            tblViewMeals.getColumnModel().getColumn(2).setResizable(false);
            tblViewMeals.getColumnModel().getColumn(3).setResizable(false);
            tblViewMeals.getColumnModel().getColumn(4).setResizable(false);
            tblViewMeals.getColumnModel().getColumn(5).setResizable(false);
        }

        lblProtien.setText("Protein:");

        lblCarbs.setText("Carbs:");

        lblCalories.setText("Calories:");

        btnAdd.setText("Add Meal Nutrition");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewMeals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarbs, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProtien, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCalories, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProtien, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtCarbs, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtCalories, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblViewMeals, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProtien))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarbs))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalories))
                .addGap(30, 30, 30)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Nutritionist nutritionist = new Nutritionist(userProcessContainer, account, enterprise, organization, business);
        business.redirection(userProcessContainer, nutritionist.getClass().getName(), nutritionist);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblViewMeals.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String protein = txtProtien.getText();
        String carbs = txtCarbs.getText();
        String calories = txtCalories.getText();
        
        if(protein.equals("") || carbs.equals("") || calories.equals("")){
            JOptionPane.showMessageDialog(this, "Please provide valid inputs", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        MealWorkRequest meal = (MealWorkRequest) tblViewMeals.getValueAt(selectedRow, 0);
        Meal m = meal.getMealByID(meal.getSendDataRequestId());
        m.setProtein(protein);
        m.setCarbs(carbs);
        m.setCalories(calories);
        meal.setStatus("Nutrition Values Added");
        populateTable();
        
        JOptionPane.showMessageDialog(this, "Nutrition Value added successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCalories;
    private javax.swing.JLabel lblCarbs;
    private javax.swing.JLabel lblProtien;
    private javax.swing.JLabel lblViewMeals;
    private javax.swing.JTable tblViewMeals;
    private javax.swing.JTextField txtCalories;
    private javax.swing.JTextField txtCarbs;
    private javax.swing.JTextField txtProtien;
    // End of variables declaration//GEN-END:variables
}
