/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Volunteer;

/**
 *
 * @author samar
 */
public class ViewHelpRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewHelpRequestsJPanel
     */
    public ViewHelpRequestsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewHelpRequests = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewHelpRequests = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnViewRequestorProfile = new javax.swing.JButton();
        btnAssigntoMe = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblViewHelpRequests.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        lblViewHelpRequests.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewHelpRequests.setText("View Help Requests");

        tblViewHelpRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Need Help", "Requestor", "Requested Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblViewHelpRequests);

        jButton1.setText("Refresh");

        btnViewRequestorProfile.setText("View Requestor Profile");

        btnAssigntoMe.setText("Assign to Me");

        btnProcess.setText("Process");

        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnViewRequestorProfile)
                        .addGap(18, 18, 18)
                        .addComponent(btnAssigntoMe)
                        .addGap(18, 18, 18)
                        .addComponent(btnProcess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblViewHelpRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblViewHelpRequests)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnViewRequestorProfile)
                    .addComponent(btnAssigntoMe)
                    .addComponent(btnProcess))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssigntoMe;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnViewRequestorProfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewHelpRequests;
    private javax.swing.JTable tblViewHelpRequests;
    // End of variables declaration//GEN-END:variables
}
