/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Donor;

import Business.Business;
import Business.Common.Donation;
import Business.Common.ValidateNumber;
import Business.Common.ValidatePhoneNumber;
import Business.Common.ValidateStrings;
import Business.Common.Validation;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.SupervisorOrganization;
import Business.UserAccount.UserAccount;
import Business.WrokQueue.DonationRequest;
import java.awt.HeadlessException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aishwarya Dhandore
 */
public class DonateMoneyJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    Organization organization;
    Business business;
    DonationRequest donationReq;

    /**
     * Creates new form DonateMoneyJPanel
     */
    public DonateMoneyJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Organization organization, Business business, DonationRequest donationRequest) {
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.account = account;
        this.enterprise = enterprise;
        this.organization = organization;
        this.donationReq = donationRequest;
        
        this.setBackground(new java.awt.Color(102, 153, 255));
        
        if (this.donationReq == null) {
            JOptionPane.showMessageDialog(null, "No donation request found", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        initComponents();
        addInputVerifiers();
        txtOrganizationName.setText(Donation.toAcNo);
    }

    private void addInputVerifiers() {
        InputVerifier noValidation = new ValidateNumber();
        txtAmountDonated.setInputVerifier(noValidation);

        InputVerifier phnumberValidation = new ValidatePhoneNumber();
        txtCardDetails.setInputVerifier(phnumberValidation);

        InputVerifier stringValidation = new ValidateStrings();
        txtName.setInputVerifier(stringValidation);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDonateForAMeal = new javax.swing.JLabel();
        lblOrganization = new javax.swing.JLabel();
        lblEnterName = new javax.swing.JLabel();
        lblEnterCardDetails = new javax.swing.JLabel();
        lblExpiryDate = new javax.swing.JLabel();
        txtOrganizationName = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtCardDetails = new javax.swing.JTextField();
        txtExpiryDate = new javax.swing.JTextField();
        lblEnterAmount = new javax.swing.JLabel();
        txtAmountDonated = new javax.swing.JTextField();
        btnDonation = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblDonateForAMeal.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblDonateForAMeal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonateForAMeal.setText("Donate for a Meal");

        lblOrganization.setText("To Account");

        lblEnterName.setText("Enter Name :");

        lblEnterCardDetails.setText("Enter Debit/Credit Card number :");

        lblExpiryDate.setText("Enter Expiry Date (MM/YYYY) :");

        txtOrganizationName.setEditable(false);

        lblEnterAmount.setText("Enter Amount to Donate :");

        btnDonation.setText("Make a donation!");
        btnDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonationActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnterName)
                    .addComponent(lblEnterCardDetails)
                    .addComponent(lblExpiryDate)
                    .addComponent(lblEnterAmount)
                    .addComponent(lblOrganization)
                    .addComponent(btnDonation))
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(txtCardDetails, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtExpiryDate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtAmountDonated, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txtOrganizationName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDonateForAMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblDonateForAMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOrganizationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrganization))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnterName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnterCardDetails)
                            .addComponent(txtCardDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblExpiryDate)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterAmount)
                    .addComponent(txtAmountDonated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnDonation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonationActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        String cardNo = txtCardDetails.getText();
        String expiry = txtExpiryDate.getText();
        String amount = txtAmountDonated.getText();

        DateFormat df = new SimpleDateFormat("EEE, MMM d, YYYY hh:mm aaa");
        Calendar cal = Calendar.getInstance();
        String timestamp = df.format(cal.getTime());

        Donation donation = account.getPerson().addDonation();

        donation.setAmount(amount);
        donation.setDonationDate(timestamp);
        donation.setAccntName(name);
        donation.setAccntNumber(cardNo);

        try {
            DonationRequest donationRequest = donationReq;
            donationRequest.setDonation(donation);
            donationRequest.setDonatedBy(account.getUserName());
            donationRequest.setMessage("Donated Money");
            donationRequest.setStatus("Approved");
            donationRequest.setResolveDate(new Date());
            JOptionPane.showMessageDialog(null, "Donation has been made successfully, Thank You", "success", JOptionPane.PLAIN_MESSAGE);
            resetFields();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Donation failed, Something went wrong", "warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnDonationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Donor donor = new Donor(userProcessContainer, account, enterprise, organization, business);
        business.redirection(userProcessContainer, donor.getClass().getName(), donor);
    }//GEN-LAST:event_btnBackActionPerformed

    public void resetFields() {
        txtExpiryDate.setText("");
        txtCardDetails.setText("");
        txtAmountDonated.setText("");
        txtName.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDonation;
    private javax.swing.JLabel lblDonateForAMeal;
    private javax.swing.JLabel lblEnterAmount;
    private javax.swing.JLabel lblEnterCardDetails;
    private javax.swing.JLabel lblEnterName;
    private javax.swing.JLabel lblExpiryDate;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JTextField txtAmountDonated;
    private javax.swing.JTextField txtCardDetails;
    private javax.swing.JTextField txtExpiryDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrganizationName;
    // End of variables declaration//GEN-END:variables
}
