/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Donor;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WrokQueue.DonationRequest;
import Business.WrokQueue.NeedMealWorkRequest;
import Business.WrokQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aniketgiram
 */
public class ProcessDonation extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    Organization organization;
    Business business;

    /**
     * Creates new form ProcessDonation
     */
    public ProcessDonation(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Organization organization, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.account = account;
        this.enterprise = enterprise;
        this.organization = organization;
        populateTable();
        this.setBackground(new java.awt.Color(102, 153, 255));
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblDonationInfo.getModel();
        model.setRowCount(0);
        for (WorkRequest w : account.getWorkQueue().getWorkRequestList()) {
            if (w instanceof DonationRequest) {
                Object row[] = new Object[5];
                DonationRequest dreq = (DonationRequest) w;
                if(!dreq.getStatus().equals("Approved")){
                    row[0] = dreq;
                    row[1] = dreq.getSender().getPerson().getName();
                    row[2] = dreq.getMessage();
                    row[3] = dreq.getReceiver();
                    row[4] = dreq.getStatus();
                    model.addRow(row);
                }
            }
        }

        if ((model.getRowCount() == 0)) {
            JOptionPane.showMessageDialog(null, "No Donation request found", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonationInfo = new javax.swing.JTable();
        lblRequestDonation = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnProcessDonation = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();

        tblDonationInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Sender", "Comment", "Reciever", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDonationInfo);

        lblRequestDonation.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        lblRequestDonation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequestDonation.setText("Process Donation");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnProcessDonation.setText("Process this donation");
        btnProcessDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessDonationActionPerformed(evt);
            }
        });

        btnAssign.setText("Assign to me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addComponent(lblRequestDonation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnAssign)
                        .addGap(18, 18, 18)
                        .addComponent(btnProcessDonation)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblRequestDonation)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnProcessDonation)
                    .addComponent(btnAssign))
                .addContainerGap(282, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Donor donor = new Donor(userProcessContainer, account, enterprise, organization, business);
        business.redirection(userProcessContainer, donor.getClass().getName(), donor);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDonationInfo.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DonationRequest req = (DonationRequest) tblDonationInfo.getValueAt(selectedRow, 0);
        req.setReceiver(account);
        req.setStatus("In Process");
        populateTable();
        JOptionPane.showMessageDialog(this, "Request Assigned to you, you can now process it", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnProcessDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessDonationActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDonationInfo.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DonationRequest req = (DonationRequest) tblDonationInfo.getValueAt(selectedRow, 0);
        if (req.getReceiver() != null) {
            DonateMoneyJPanel donateMoneyJPanel = new DonateMoneyJPanel(userProcessContainer, account, enterprise, organization, business, req);
            business.redirection(userProcessContainer, donateMoneyJPanel.getClass().getName(), donateMoneyJPanel);
        } else {
            JOptionPane.showMessageDialog(this, "Please Assign the request first", "warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnProcessDonationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcessDonation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRequestDonation;
    private javax.swing.JTable tblDonationInfo;
    // End of variables declaration//GEN-END:variables
}
